// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/pr-repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pullrequest "github.com/JanArsMAI/PullRequestService/internal/domain/pullrequest"
	team "github.com/JanArsMAI/PullRequestService/internal/domain/team"
	user "github.com/JanArsMAI/PullRequestService/internal/domain/user"
	gomock "github.com/golang/mock/gomock"
)

// MockPullRequestRepo is a mock of PullRequestRepo interface.
type MockPullRequestRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepoMockRecorder
}

// MockPullRequestRepoMockRecorder is the mock recorder for MockPullRequestRepo.
type MockPullRequestRepoMockRecorder struct {
	mock *MockPullRequestRepo
}

// NewMockPullRequestRepo creates a new mock instance.
func NewMockPullRequestRepo(ctrl *gomock.Controller) *MockPullRequestRepo {
	mock := &MockPullRequestRepo{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepo) EXPECT() *MockPullRequestRepoMockRecorder {
	return m.recorder
}

// AddPR mocks base method.
func (m *MockPullRequestRepo) AddPR(ctx context.Context, pr pullrequest.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPR", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPR indicates an expected call of AddPR.
func (mr *MockPullRequestRepoMockRecorder) AddPR(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPR", reflect.TypeOf((*MockPullRequestRepo)(nil).AddPR), ctx, pr)
}

// AddReviewerToPR mocks base method.
func (m *MockPullRequestRepo) AddReviewerToPR(ctx context.Context, prId, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReviewerToPR", ctx, prId, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReviewerToPR indicates an expected call of AddReviewerToPR.
func (mr *MockPullRequestRepoMockRecorder) AddReviewerToPR(ctx, prId, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReviewerToPR", reflect.TypeOf((*MockPullRequestRepo)(nil).AddReviewerToPR), ctx, prId, reviewerID)
}

// AddTeam mocks base method.
func (m *MockPullRequestRepo) AddTeam(ctx context.Context, name string, users []user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", ctx, name, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTeam indicates an expected call of AddTeam.
func (mr *MockPullRequestRepoMockRecorder) AddTeam(ctx, name, users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*MockPullRequestRepo)(nil).AddTeam), ctx, name, users)
}

// GetPr mocks base method.
func (m *MockPullRequestRepo) GetPr(ctx context.Context, prID string) (*pullrequest.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPr", ctx, prID)
	ret0, _ := ret[0].(*pullrequest.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPr indicates an expected call of GetPr.
func (mr *MockPullRequestRepoMockRecorder) GetPr(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPr", reflect.TypeOf((*MockPullRequestRepo)(nil).GetPr), ctx, prID)
}

// GetTeam mocks base method.
func (m *MockPullRequestRepo) GetTeam(ctx context.Context, id int) (*team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, id)
	ret0, _ := ret[0].(*team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockPullRequestRepoMockRecorder) GetTeam(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockPullRequestRepo)(nil).GetTeam), ctx, id)
}

// GetTeamByName mocks base method.
func (m *MockPullRequestRepo) GetTeamByName(ctx context.Context, name string) (*team.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, name)
	ret0, _ := ret[0].(*team.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockPullRequestRepoMockRecorder) GetTeamByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockPullRequestRepo)(nil).GetTeamByName), ctx, name)
}

// GetTeamPr mocks base method.
func (m *MockPullRequestRepo) GetTeamPr(ctx context.Context, teamID int) ([]pullrequest.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamPr", ctx, teamID)
	ret0, _ := ret[0].([]pullrequest.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamPr indicates an expected call of GetTeamPr.
func (mr *MockPullRequestRepoMockRecorder) GetTeamPr(ctx, teamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamPr", reflect.TypeOf((*MockPullRequestRepo)(nil).GetTeamPr), ctx, teamID)
}

// GetUserByID mocks base method.
func (m *MockPullRequestRepo) GetUserByID(ctx context.Context, userID string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockPullRequestRepoMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockPullRequestRepo)(nil).GetUserByID), ctx, userID)
}

// GetUserWithTeam mocks base method.
func (m *MockPullRequestRepo) GetUserWithTeam(ctx context.Context, userID string) (*user.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithTeam", ctx, userID)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserWithTeam indicates an expected call of GetUserWithTeam.
func (mr *MockPullRequestRepoMockRecorder) GetUserWithTeam(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithTeam", reflect.TypeOf((*MockPullRequestRepo)(nil).GetUserWithTeam), ctx, userID)
}

// GetUsersPr mocks base method.
func (m *MockPullRequestRepo) GetUsersPr(ctx context.Context, userId string, onlyActive bool) ([]pullrequest.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersPr", ctx, userId, onlyActive)
	ret0, _ := ret[0].([]pullrequest.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersPr indicates an expected call of GetUsersPr.
func (mr *MockPullRequestRepoMockRecorder) GetUsersPr(ctx, userId, onlyActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersPr", reflect.TypeOf((*MockPullRequestRepo)(nil).GetUsersPr), ctx, userId, onlyActive)
}

// RemoveReviewerFromAllPR mocks base method.
func (m *MockPullRequestRepo) RemoveReviewerFromAllPR(ctx context.Context, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReviewerFromAllPR", ctx, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReviewerFromAllPR indicates an expected call of RemoveReviewerFromAllPR.
func (mr *MockPullRequestRepoMockRecorder) RemoveReviewerFromAllPR(ctx, reviewerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReviewerFromAllPR", reflect.TypeOf((*MockPullRequestRepo)(nil).RemoveReviewerFromAllPR), ctx, reviewerID)
}

// UpdatePr mocks base method.
func (m *MockPullRequestRepo) UpdatePr(ctx context.Context, prId string, newPr pullrequest.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePr", ctx, prId, newPr)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePr indicates an expected call of UpdatePr.
func (mr *MockPullRequestRepoMockRecorder) UpdatePr(ctx, prId, newPr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePr", reflect.TypeOf((*MockPullRequestRepo)(nil).UpdatePr), ctx, prId, newPr)
}

// UpdateUser mocks base method.
func (m *MockPullRequestRepo) UpdateUser(ctx context.Context, u user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockPullRequestRepoMockRecorder) UpdateUser(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockPullRequestRepo)(nil).UpdateUser), ctx, u)
}
